#!/usr/bin/env bash
echo "Installing build dependecies"
npm install
godep restore
echo "Compiling Assets"
gulp build
echo "Compjing Javascript"
browserify -t coffee-reactify -t reactify assets/js/app/app.coffee -o static/js/build.js -d
echo "Done, launch the server with: 'go run server/server.go'"
