---
driver:
  name: vagrant
  synced_folders:
    - ["../../", "/bursa"]

provisioner:
  name: chef_solo
  network:
    - ["private_network", { ip: "10.1.3.7" }]

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[bursa::default]
    attributes:
