---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "10.1.3.7" }]
  synced_folders:
    - ["../../", "/bursa", "create: true"]
  customize:
    memory: 512
    cpus: 2

driver_config:
    require_chef_omnibus: true

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[all]
      - recipe[bursa::default]
    attributes:
