source "https://supermarket.getchef.com"
source "https://api.berkshelf.com"

metadata

Dir.glob('../*').each do |path|
  # Skip myself.
  unless File.basename(path) == 'bursa'
    cookbook File.basename(path), path: path
  end
end
